#!/usr/bin/env bash

set -e

mkdir -p build/

cd build/

cmake \
    -C../configs/imx6_sabre_lite.cmake \
    -DCROSS_COMPILER_PREFIX=arm-linux-gnueabihf- \
    -DCMAKE_TOOLCHAIN_FILE=../kernel/gcc.cmake \
    -G Ninja ..

cmake ..

ninja

exit 0
